tomorrow505/auto_feed_js

auto_feed.user.js
1. 支持jptv 转入
2. 修复blu, ACM 转入截图
=> 1. 支持jptv 转入   2. 修复blu, ACM 转入截图

auto_feed.user.js
修复因为大青虫升级1.8后，质量和标签无法正常填充和显示的问题
=> fix(CyanBug):修复大青虫升级1.8后无法填充质量的问题

auto_feed.user.js
=> 新增支持 SRVFI

auto_feed.user.js
=> 增加对西电睿思种子转入支持

auto_feed.user.js
=> 增加GGPT和OKPT两个站点

auto_feed.user.js
=> update DICMusic url

auto_feed.user.js
支持PTLSP
PTLSP为一个综合站点
合并了最新代码并且更新了站点logo
=> support PTLSP

auto_feed.user.js
fix: 修复DramaS@ADWeb无法识别声明感谢
fix: 修复HaiDan加载图标失败
=> fix: 修复DramaS@ADWeb无法识别声明感谢

auto_feed.user.js
=> support Ptvicomo

auto_feed.user.js
Agsv 为 Arctic global seed vault 的缩写，中文名为末日种子库
Agsv为一个综合站点
=> support Agsv

auto_feed.user.js
=> fix（Agsv&ptvicomo） tag

auto_feed.user.js
=> fix（Agsv） support agsv specialcat

auto_feed.user.js
=> fix（Agsv） add new team

auto_feed.user.js
=> fix(agsv) support DD DDP EAC3

auto_feed.user.js
=> fix okpt's team processing

auto_feed.user.js
Agsv change name AGSV，supprot new theme domain
=> fix(AGSV) Agsv change name AGSV，supprot new theme domain

auto_feed.user.js
=> 更新ecustpt地址

auto_feed.user.js
=> update PTvicomo Domain and Category ID

auto_feed.user.js
1. Fix site error caused by Array.prototype.remove conflict
2. Implement ant-design form filler and support filling in all fields
=> Support YemaPT

auto_feed.user.js
1. str.slice 不匹配导致的结尾缺字符
2. url 中 携带了 &uploaded=1 参数时，获取主标题错误。
=> fix(HDArea): 修复了 HDA 转出到其他站点时的问题。

auto_feed.user.js
- 重新适配hd4fans
- 更新/添加iloli的一些TAG适配
- MDU转出副标题获取，MDU转出类型动漫匹配
- U2转出年份获取根据anidb数据，之前获取方式会有BUG
- 我的IED好像去除了些无用的行尾空格，这个不是故意的，不过好像问题不大。
=> fix hd4fans iloli mdu u2

auto_feed.user.js
=> Update config for HITPT

auto_feed.user.js
=> fix add AGSV backup domain

auto_feed.user.js
=> feat:适配站点 ptlover

auto_feed.user.js
=> feat: add support for new site "财神“

auto_feed.user.js
=> support AGSV ark tag
